version: '2.1'

services:
  frontend:
    container_name: frontend
    image: ${PRIVATE_REGISTRY}${DOCKER_IMAGE:-digi-doc-frontend}:${DOCKER_TAG:-latest}
    networks:
      dogi-doc-network:
        aliases:
          - frontend

networks:
  digi-doc-network:
    name: digi-doc-network
